name: release-build

on:
  release:
    types: [published]

jobs:
  build-windows:
    name: "Build Windows Installer"
    runs-on: "windows-2022"

    env:
      CARGO_INCREMENTAL: "0"
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
      RUSTUP_WINDOWS_PATH_ADD_BIN: "1"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: "Install Rust"
        uses: dtolnay/rust-toolchain@stable
        with:
          target: "x86_64-pc-windows-msvc"
      - name: "Compile with sccache"
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: "Cache Rust Dependencies"
        uses: actions/cache@v4
        id: cache-cargo-vendor
        with:
          path: |
            vendor
            .cargo/config
          key: "cargo-deps-${{ hashFiles('**/Cargo.lock') }}"
      - name: "Vendor dependencies"
        if: steps.cache-cargo-vendor.outputs.cache-hit != 'true'
        shell: bash
        run: "cargo vendor --locked --versioned-dirs >> .cargo/config"
      - name: "Build wezterm (Release mode)"
        shell: cmd
        run: |
          PATH C:\Strawberry\perl\bin;%PATH%
          cargo build -p wezterm --release
      - name: "Build wezterm-gui (Release mode)"
        shell: cmd
        run: |
          PATH C:\Strawberry\perl\bin;%PATH%
          cargo build -p wezterm-gui --release
      - name: "Build wezterm-mux-server (Release mode)"
        shell: cmd
        run: |
          PATH C:\Strawberry\perl\bin;%PATH%
          cargo build -p wezterm-mux-server --release
      - name: "Build strip-ansi-escapes (Release mode)"
        shell: cmd
        run: |
          PATH C:\Strawberry\perl\bin;%PATH%
          cargo build -p strip-ansi-escapes --release
      - name: "Install cargo-nextest"
        uses: baptiste0928/cargo-install@v3
        with:
          crate: "cargo-nextest"
          cache-key: "windows"
      - name: "Test"
        shell: cmd
        run: |
          PATH C:\Strawberry\perl\bin;%PATH%
          cargo nextest run --all --no-fail-fast
      - name: "Package"
        shell: bash
        run: "bash ci/deploy.sh"
      - name: "Upload artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: "windows"
          path: |
            WezTerm-*.zip
            WezTerm-*.exe
      - name: "Checksum"
        shell: bash
        run: |
          for f in WezTerm-*.zip WezTerm-*.exe ; do
            sha256sum "$f" > "$f.sha256"
          done
      - name: "Upload to Release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          gh release upload --clobber "${{ github.event.release.tag_name }}" \
            WezTerm-*.zip WezTerm-*.exe *.sha256

  build-macos:
    name: "Build macOS"
    runs-on: "macos-latest"

    env:
      CARGO_INCREMENTAL: "0"
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
      MACOSX_DEPLOYMENT_TARGET: "10.12"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: "Install Rust (ARM)"
        shell: bash
        run: "rustup target add aarch64-apple-darwin"
      - name: "Install Rust (Intel)"
        shell: bash
        run: "rustup target add x86_64-apple-darwin"
      - name: "Compile with sccache"
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: "Cache Rust Dependencies"
        uses: actions/cache@v4
        id: cache-cargo-vendor
        with:
          path: |
            vendor
            .cargo/config
          key: "cargo-deps-${{ hashFiles('**/Cargo.lock') }}"
      - name: "Vendor dependencies"
        if: steps.cache-cargo-vendor.outputs.cache-hit != 'true'
        shell: bash
        run: "cargo vendor --locked --versioned-dirs >> .cargo/config"
      - name: "Install System Deps"
        shell: bash
        run: "env CI=yes PATH=$PATH ./get-deps"
      - name: "Build wezterm (Release mode Intel)"
        shell: bash
        run: "cargo build --target x86_64-apple-darwin -p wezterm --release"
      - name: "Build wezterm (Release mode ARM)"
        shell: bash
        run: "cargo build --target aarch64-apple-darwin -p wezterm --release"
      - name: "Build wezterm-gui (Release mode Intel)"
        shell: bash
        run: "cargo build --target x86_64-apple-darwin -p wezterm-gui --release"
      - name: "Build wezterm-gui (Release mode ARM)"
        shell: bash
        run: "cargo build --target aarch64-apple-darwin -p wezterm-gui --release"
      - name: "Build wezterm-mux-server (Release mode Intel)"
        shell: bash
        run: "cargo build --target x86_64-apple-darwin -p wezterm-mux-server --release"
      - name: "Build wezterm-mux-server (Release mode ARM)"
        shell: bash
        run: "cargo build --target aarch64-apple-darwin -p wezterm-mux-server --release"
      - name: "Build strip-ansi-escapes (Release mode Intel)"
        shell: bash
        run: "cargo build --target x86_64-apple-darwin -p strip-ansi-escapes --release"
      - name: "Build strip-ansi-escapes (Release mode ARM)"
        shell: bash
        run: "cargo build --target aarch64-apple-darwin -p strip-ansi-escapes --release"
      - name: "Install cargo-nextest"
        uses: baptiste0928/cargo-install@v3
        with:
          crate: "cargo-nextest"
          cache-key: "macos"
      - name: "Test"
        shell: bash
        run: "cargo nextest run --all --no-fail-fast --target=x86_64-apple-darwin"
      - name: "Package"
        env:
          MACOS_APPLEID: ${{ secrets.MACOS_APPLEID }}
          MACOS_APP_PW: ${{ secrets.MACOS_APP_PW }}
          MACOS_CERT: ${{ secrets.MACOS_CERT }}
          MACOS_CERT_PW: ${{ secrets.MACOS_CERT_PW }}
          MACOS_TEAM_ID: ${{ secrets.MACOS_TEAM_ID }}
        shell: bash
        run: "bash ci/deploy.sh"
      - name: "Upload artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: "macos"
          path: "WezTerm-*.zip"
      - name: "Checksum"
        shell: bash
        run: |
          for f in WezTerm-*.zip ; do
            sha256sum "$f" > "$f.sha256"
          done
      - name: "Upload to Release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          gh release upload --clobber "${{ github.event.release.tag_name }}" \
            WezTerm-*.zip *.sha256

  build-rockylinux:
    name: "Build Rocky Linux RPM"
    runs-on: "ubuntu-latest"
    container: "quay.io/centos/centos:stream9"

    env:
      CARGO_INCREMENTAL: "0"
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"

    steps:
      - name: "Install config manager"
        run: "dnf install -y 'dnf-command(config-manager)'"
      - name: "Enable CRB repo"
        run: "dnf config-manager --set-enabled crb"
      - name: "Install git"
        run: "yum install -y git"
      - name: "Install curl-minimal"
        run: "yum install -y curl-minimal"
      - name: "Ensure /run/sshd exists"
        run: "mkdir -p /run/sshd"
      - name: "Install openssh-server"
        run: "yum install -y openssh-server"
      - name: "Workaround git permissions issue"
        run: "git config --global --add safe.directory /__w/wezterm/wezterm"
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: "Install Rust"
        uses: dtolnay/rust-toolchain@stable
      - name: "Compile with sccache"
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: "Cache Rust Dependencies"
        uses: actions/cache@v4
        id: cache-cargo-vendor
        with:
          path: |
            vendor
            .cargo/config
          key: "cargo-deps-${{ hashFiles('**/Cargo.lock') }}"
      - name: "Vendor dependencies"
        if: steps.cache-cargo-vendor.outputs.cache-hit != 'true'
        run: "cargo vendor --locked --versioned-dirs >> .cargo/config"
      - name: "Install System Deps"
        run: "env CI=yes PATH=$PATH ./get-deps"
      - name: "Build wezterm (Release mode)"
        run: "cargo build -p wezterm --release"
      - name: "Build wezterm-gui (Release mode)"
        run: "cargo build -p wezterm-gui --release"
      - name: "Build wezterm-mux-server (Release mode)"
        run: "cargo build -p wezterm-mux-server --release"
      - name: "Build strip-ansi-escapes (Release mode)"
        run: "cargo build -p strip-ansi-escapes --release"
      - name: "Install cargo-nextest"
        uses: baptiste0928/cargo-install@v3
        with:
          crate: "cargo-nextest"
          cache-key: "centos9"
      - name: "Test"
        run: "cargo nextest run --all --no-fail-fast"
      - name: "Package"
        run: "bash ci/deploy.sh"
      - name: "Move RPM"
        run: "mv ~/rpmbuild/RPMS/*/*.rpm ."
      - name: "Upload artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: "rockylinux"
          path: "wezterm-*.rpm"
      - name: "Checksum"
        run: |
          for f in wezterm-*.rpm ; do
            sha256sum "$f" > "$f.sha256"
          done
      - name: "Upload to Release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload --clobber "${{ github.event.release.tag_name }}" \
            wezterm-*.rpm *.sha256
