name: unit-tests

on:
  push:
    branches:
      - main
    paths:
      - "**/*.rs"
      - "**/Cargo.lock"
      - "**/Cargo.toml"
      - ".github/workflows/unit-tests.yml"
  pull_request:
    branches:
      - main
    paths:
      - "**/*.rs"
      - "**/Cargo.lock"
      - "**/Cargo.toml"
      - ".github/workflows/unit-tests.yml"

jobs:
  test-linux:
    name: "Unit Tests (Linux)"
    runs-on: ubuntu-latest

    env:
      CARGO_INCREMENTAL: "0"
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: "Install Rust"
        uses: dtolnay/rust-toolchain@stable
      - name: "Compile with sccache"
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: "Cache Rust Dependencies"
        uses: actions/cache@v4
        id: cache-cargo-vendor
        with:
          path: |
            vendor
            .cargo/config
          key: "cargo-deps-${{ hashFiles('**/Cargo.lock') }}"
      - name: "Vendor dependencies"
        if: steps.cache-cargo-vendor.outputs.cache-hit != 'true'
        run: "cargo vendor --locked --versioned-dirs >> .cargo/config"
      - name: "Install System Deps"
        run: "env CI=yes PATH=$PATH ./get-deps"
      - name: "Install cargo-nextest"
        uses: baptiste0928/cargo-install@v3
        with:
          crate: "cargo-nextest"
          cache-key: "linux"
      - name: "Run Tests"
        run: "cargo nextest run --all --no-fail-fast"

  test-windows:
    name: "Unit Tests (Windows)"
    runs-on: "windows-2022"

    env:
      CARGO_INCREMENTAL: "0"
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
      RUSTUP_WINDOWS_PATH_ADD_BIN: "1"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: "Install Rust"
        uses: dtolnay/rust-toolchain@stable
        with:
          target: "x86_64-pc-windows-msvc"
      - name: "Compile with sccache"
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: "Cache Rust Dependencies"
        uses: actions/cache@v4
        id: cache-cargo-vendor
        with:
          path: |
            vendor
            .cargo/config
          key: "cargo-deps-${{ hashFiles('**/Cargo.lock') }}"
      - name: "Vendor dependencies"
        if: steps.cache-cargo-vendor.outputs.cache-hit != 'true'
        shell: bash
        run: "cargo vendor --locked --versioned-dirs >> .cargo/config"
      - name: "Install cargo-nextest"
        uses: baptiste0928/cargo-install@v3
        with:
          crate: "cargo-nextest"
          cache-key: "windows"
      - name: "Run Tests"
        shell: cmd
        run: |
          PATH C:\Strawberry\perl\bin;%PATH%
          cargo nextest run --all --no-fail-fast
